# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e8780ba68b872683d11177fa8af95ce807af5fff335c820cf270a1cd7e91c18ccdf177d474e7e538dc432f3ca0613fd074ded0d8cd51c19fc5e9bd23d0fe508

test:
  secret_key_base: f14cda63a5968e328d7f1be670f34aeab89d217b592fd1148ae0758bbc917c37f89e6418659dfbb41f55247bf51b1f38799e1dbb8cd4aa062a9cfa0ab2b57175

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
